### ISSUE TITLE
Chapter 6: "Pattern matching with lists" should use example from end of Ch4

### ISSUE THREAD

**Issue by ShalokShalom** [radar/joyofelixir#23]
https://joyofelixir.com/4-marvellous-maps/
How to call the example on the bottom, since there is no `person =` anymore involved?

**Comment by radar** [comment]
Hi again,

We don't have the requisite knowledge on how to do this until Chapter 6, when we talk about "Pattern matching with lists". What I am trying to show here is that you can combine the two data types of lists and maps very easily. Accessing the elements in the lists doesn't come until later.

I think that example in Chapter 6 should be updated to use this code block from the end of Chapter 4, rather than the one from Chapter 3. This is because it follows more closely what you'd typically be doing in an Elixir application: iterating through a list of maps and pulling out a particular set of keys from that map, rather than a list of strings. 

Thanks for asking!
