### ISSUE TITLE
Chapter 5 - No instructions as to IO functions

### ISSUE THREAD

**Issue by adrianmancuso** [radar/joyofelixir#27]
In the section on functions ([https://joyofelixir.com/5-funky-functions/]) the last exercise is: 

> Save either of these two solutions in their own file and run them through the elixir command-line tool.

Up to this point the book is super easy to follow but there's no instructions regarding IO functions nor any indication as to what to research online to solve the problem.  As the book seems to be aimed at programming beginners I feel this could be pretty confusing and disheartening.

It could be a good opportunity to allow the reader to use outside documentation to problem solve if some clear hints or pointers were provided

**Comment by radar** [comment]
Hi Adrian,

Thanks for opening an issue!

By saving these files I meant simply to save them through your text editor. We don't start talking about IO until Chapter 11, and even then it will be very simple files, not Elixir scripts, that we'll be writing then.

I should probably clarify here so that others aren't tripped up too.
